# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

trainSESOM <- function(Data, BMUs, RadiusVector, N, DIM, MinData, MaxData, Lines, Columns, Weights, toroid, NumDataPerEpoch) {
    .Call(`_GeneralizedUmatrixGPU_trainSESOM`, Data, BMUs, RadiusVector, N, DIM, MinData, MaxData, Lines, Columns, Weights, toroid, NumDataPerEpoch)
}

